development:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  database: comet_development
  pool: 5
  username: root
  password: 'jkilopqcv0968'
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: comet_test
  pool: 5
  username: root
  password: 'jkilopqcv0968'
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: comet_production
  pool: 5
  username: root
  password: 'jkilopqcv0968'

  socket: /tmp/mysql.sock


# ------------------ windows 下用下面的配置 --------------

#default: &default
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#
#development:
#  <<: *default
#  database: db/development.sqlite3
#
#test:
#  <<: *default
#  database: db/test.sqlite3
#
#production:
#  <<: *default
#  database: db/production.sqlite3